caterwaul.module( 'serialization' ,function($) {$.serialization= (function( ) {var statics= {unknown: (function(it) {return($.merge(it.prototype, {toString:function() {;
return( '<#unknown ' + (this.id) + '>' ) } } ) ) ,it} ) .call(this, (function(_) {return(function(it) {return(it.id=_) ,it} ) .call(this, (this) ) } ) ) } ,base62_characters= 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789' ,key=function() {;
return(function(it) {return( ( '_' + (it.join( "" ) ) + '' ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (base62_characters.charAt(Math.random() *62>>>0) ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (0) , (22) , (1) ) ) ) ) } ,precoded_values= [void 0,null,false,true, '' / '' , -1/0,1/0,0, '' ] ,structural_reference_types= [Boolean,Number,String,Array,Object,Date,RegExp,Function] ,shift=precoded_values.length,shift1=shift-1,encoder=function(locals,k,xs,c) {;
var result=function(v) {;
return(function( ) {var ref_detector=new String(key() ) ,is_precoded=function(v) {;
return!v||v.constructor===Number&& ( ( !isFinite(v) ) || (isNaN(v) ) ) ||v===true} ,is_reference=function(v) {;
return( [ 'object' , 'function' ] ) .indexOf(typeof v) !== -1} ,precoded_index_of=function(v) {;
return(function(it) {return(it=== -1&&isNaN(v) ?4:it) } ) .call(this, ( (precoded_values) .indexOf(v) ) ) } ,is_opaque=function(v) {;
return(structural_reference_types) .indexOf(v.constructor) === -1} ,is_unknown=function(v) {;
return v.constructor===$.serialization.unknown} ,local_key_for=function(v) {;
return is_unknown(v) ?v.id:key() } ,position_of=function(v) {;
return is_precoded(v) ?new Number(precoded_index_of(v) ) :is_reference(v) ?v[k] :c[ ( '@' + ( (typeof v) .charAt(0) ) + '' + (v) + '' ) ] } ,store=function(v) {;
return is_reference(v) ? (function(it) {return(visit(v) ) ,it} ) .call(this, ( (function( ) {var k=local_key_for(v) ;
return(store_reference(locals[k] =v,k) ) } ) .call(this) ) ) :c[ ( '@' + ( (typeof v) .charAt(0) ) + '' + (v) + '' ) ] =shift1+ (xs) .push(v) } ,store_reference=function(v,i) {;
return v[k] =shift1+ (xs) .push( [type_of(v) ,i,value_of(v) , [ ] ] ) } ,type_of=function(v) {;
return(structural_reference_types) .indexOf(v.constructor) +1} ,value_of=function(v) {;
return v.constructor===Boolean||v.constructor===Number||v.constructor===Date?encode(v.valueOf() ) :v.constructor===String||v.constructor===RegExp||v.constructor===Function?encode(v.toString() ) : [ ] } ,visit=function(v) {;
return(function( ) {var is_array=v instanceof Array,ref=xs[position_of(v) -shift] ,encode_pair=function(p) {;
return(ref[3] ) .push(encode(p[0] ) ,encode(p[1] ) ) } ,is_array_index=function(v,p) {;
return/^\d+$/ .test(p) && +p>=0&& +p<v.length} ,link_properties=function(v,is_array) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (encode_pair) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length,x0;
xi<xl;
 ++xi)x=xs[xi] , (x[0] !==k&& ( ( !is_array) || ( !is_array_index(v,x[0] ) ) ) ) &&xr.push(x) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (v) ) ) ) } ,link_array_elements=function(v) {;
return ref[2] = (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (encode) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this,Array.prototype.slice.call( (v) ) ) } ;
return( ( ! (is_opaque(v) ) && ( (function(it) {return( ( (is_array) && (link_array_elements(v) ) ) ) ,it} ) .call(this, (link_properties(v,is_array) ) ) ) ) ) } ) .call(this) } ;
return( (function(it) {return( +it) } ) .call(this, ( ( (position_of(v) ) || (store(v) ) ) ) ) ) } ) .call(this) } ;
var encode=result;
return result} ,decode=function(locals,xs) {;
return(function( ) {var was_local= { } ,reconstitute=function(o,i) {;
return o.constructor===Array? (was_local[i] =locals[o[1] ] ) ||reconstitute_reference(o,xs) :o} ,reconstitute_reference=function(o) {;
return o[0] ===4? [ ] :o[0] ===8?safely_rebuild_function(ref(xs,o[2] ) ) :o[0] ===7? (function(it) {return(new RegExp(it[1] ,it[2] ) ) } ) .call(this, ( /^\/(.*)\/([^\/]*)$/ .exec(ref(xs,o[2] ) ) ) ) :o[0] &&o[0] <=8?new structural_reference_types[o[0] -1] (ref(xs,o[2] ) ) :new $.serialization.unknown(o[1] ) } ,ref=function(xs,index) {;
return index>=shift?xs[index-shift] :precoded_values[index] } ,safely_rebuild_function=function(code) {;
return(function( ) {var parsed= ($) .parse(code) ,looks_like_a_function=function(t) {;
return t.data=== 'function' &&t[0] .data=== '(' &&t[1] .data=== '{' } ;
return( ( (looks_like_a_function(parsed) ||parsed[0] .data=== '(' &&looks_like_a_function(parsed[0] ) ) && ( ($) .compile(parsed) ) ) ) } ) .call(this) } ,relink=function(serialized,objects) {;
return(function( ) {var has_links=function(x) {;
return x.constructor===Array&& !was_local[this.xi] } ,has_indexes=function(x) {;
return has_links(x) &&x[0] ===4} ,link_object_properties=function(s) {var o=objects[this.xi] ;
return( (has_links(s) ) && ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (o[ref(objects,x) ] =ref(objects,xs[ ++xi] ) ) ;
return xs} ) .call(this,s[3] ) ) ) } ,link_array_properties=function(s) {var o=objects[this.xi] ;
return( (has_indexes(s) ) && ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (o.push(ref(objects,x) ) ) ;
return xs} ) .call(this,s[2] ) ) ) } ;
return( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (link_array_properties) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (link_object_properties) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this,serialized) ) ) } ) .call(this) } ,values= (function(it) {return(relink(xs,it) ) ,it} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (reconstitute(x,xi) ) ) ;
return xr} ) .call(this,xs) ) ) ;
return(ref(values,values.pop() ) ) } ) .call(this) } ,stream=function(options) {;
var result= (function( ) {var settings=$.merge( {opaques:true} ,options) ,unmark=function(xs,k) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( ( (x.constructor===Array) && (delete self.locals[x[1] ] [k] ) ) ) ;
return xs} ) .call(this,xs) } ,erase=function(xs) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( ( (x.constructor===Array) && (x[1] =0) ) ) ;
return xs} ) .call(this,xs) } ,postprocess=function(xs,k) {;
return( (unmark(xs,k) ) , ( ( ! (settings.opaques) && (erase(xs) ) ) ) ) } ,local_encode=function(v) {;
return(function( ) {var k=key() ,xs= [ ] ,value_index=encoder(self.locals,k,xs, { } ) (v) ;
return( ( ( ( ( (xs) .push(value_index) ) , (postprocess(xs,k) ) ) ) , (xs) ) ) } ) .call(this) } ,local_decode=function(v) {;
return decode(self.locals,v) } ;
return($.merge(function(_) {return(self) .encode(_) } , {locals: { } ,encode:local_encode,decode:local_decode} ) ) } ) .call(this) ;
var self=result;
return result} ;
return($.merge(stream,statics) ) } ) .call(this) } ) ;
